import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section className="w-full h-full">
        <div className="absolute left-1/2 top-1/4 border-2">
          안녕하세요
        </div>
        <div className="absolute left-1/4 top-1/2">
          <div>
            테스트 문구입니다?
          </div>
          <div className="absolute right-1/4">
            테스트 문구가 아닙니다?
          </div>
          
        </div>
      </section>
      
    </div>
  )
}

export default Home
